<a href="https://colab.research.google.com/github/yeaeunJi/Algorithm_hackerrank/blob/main/Chapter1_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%B3%B5%EC%8A%B5_%EC%88%98%ED%95%99%EA%B3%BC_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 벡터와 행렬
- 신경망에서는 '벡터'와 '행렬' 또는 '텐서(tensor)'가 중요함
  - 벡터 : 크기와 방향을 가진 양. 숫자가 일렬로 늘어선 집합(파이썬에서는 1차원 배열 취급 가능)
  - 행렬 : 2차원 형태로 숫자를 늘여놓은 것
  - 텐서 : 숫자집합을 N차원으로 표현한 것|



## 벡터 
- 벡터는 단순한 개념이지만 이를 표현하는 방법은 열벡터, 행벡터가 존재
  - 열벡터 : 숫자들을 세로로 나열하는 방법
  - 행벡터 : 숫잘들을 가로로 나열하는 방법
- 수학과 딥러닝 등 많은 분야에서 '열벡터'방식 선호하지만 이 책에서는 '행벡터'를 다룰 것임

In [5]:
# 벡터 생성 : np.array() 메소드로 생성 가능
import numpy as np
x = np.array([1,2,3]) # ==> numpy의 다차원 배열 클래스인 np.ndarray 클래스를 생성
print(x)
x.__class__ # 클래시 이름 표시.

[1 2 3]


numpy.ndarray

In [2]:
x.shape # 인스턴스 변수 중 다차원 배열의 형상(모양)에 관한 변수

(3,)

In [3]:
x.ndim # 인스턴스 변수 중 다차원 배열의 차원 수를 담고 있는 변수

1

In [4]:
# 행렬 생성
W = np.array([[1,2,3], [4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


### 행렬의 원소별 연산(elements-wise)
- 더하기(+)와 곱하기(*) 연산 : 피연산자인 다차원 배열들에서 서로 대응하는 원소끼리(각 원소가 독립적으로) 연산된다.

In [7]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
print(W+X)
print(W*X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


### 브로드캐스트(broadcast)
- 형상(모양)이 다른 다차원 배열끼리의 연산도 가능

In [9]:
A = np.array([[1,2], [3,4]])
A * 10 # 2차원 배열에 스칼라값을 곱할 경우, 스칼라 값이 A의 형상으로 확장되어 원소별 연산을 수행한다.

array([[10, 20],
       [30, 40]])

In [10]:
A = np.array([[1,2], [3,4]])
b = np.array([10, 20])
A * b # 2차원 배열A와 1차원 배열 b를 곱할 경우, 1차원 배열인 b가 2차원 배열 A의 형상과 같아지도록 활장되어 원소별 연산을 수행한다.

# 넘파이의 브로드캐스트가 효과적으로 동작하기 위해선 다차원 배열의 형상이 몇 가지 규칙을 충족해야 한다. 

array([[10, 40],
       [30, 80]])

### 벡터의 내적과 행렬의 곱
- 벡터의 내적 : 두 벡터에서 대응하는 원소들의 곱을 모두 더한 것

    예) 두 개의 벡터 
      x = (x1, x2, ..., xn)
      y = (y1, y2, ..., yn)

    벡터의 내적 수식 : x*y = x1y1 + x2y2 + ... + xnyn

- 벡터의 내적은 '두 벡터가 얼마나 같은 방향으로 향하고 있는가'를 나타낸다.

  벡터의 길이가 1인 경우, 완전히 같은 방향으로 향하는 두 벡터의 내적은 1이된다. 반대로, 반대 방향을 향하는 두 벡터의 내적은 -1이다.

- 행렬의 곱 : 왼쪽 행렬의 행벡터와 오른쪽 행렬의 열벡터의 내적을 새로운 행렬의 대응하는 원소에 저장


In [11]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)

32

In [14]:
# 행렬의 곱
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(np.matmul(A,B))
print(A*B)
print(np.dot(A,B)) # 벡터의 내적과 행렬의 곱 모두에 np.dot() 사용 가능. 다만 이 둘의 구분을 통해 코드의 논리와 의도가 명확해질 수 있음

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


### 행렬 형상 확인
- 형상(shape) 확인 

    행렬의 곱에서는 대응하는 차원의 원소 수를 일치시킨다.

    행렬 A와 B를 곱하여 행렬 C를 만든다면, A의 열과 B의 행이 같아야 한다.
    이렇게 만들어진 행렬 C의 형상은 A의 행 수와 B의 열 수가 된다.

## 신경망의 추론
- 신경망에서 수행하는 작업은 두 단계로 나눌 수 있다. '학습'과 '추론'이다.


### 신경망 추론 전체 그림
- 신경망은 간단히 말하면 단순한 '함수'라고 할 수 있다. 입력한 값을 처리를 통해 어떠한 값으로 출력하는 함수와 같이 신경망 역시 입력을 출력으로 변환한다.



In [ ]:
# 예) 2차원 데이터를 입력하여 3차원 데이터를 출력하는 함수를 신경망으로 구현하려면
# 입력층(input layer) ==> 뉴런 2개
# 출력층(output layer) ==> 3개
# 은닉층(hidden layer) 혹은 중간층 ==> 적당한 층의 뉴런 배치

# 입력층 A -----가충치(weight) 존재----> 은닉층
# 가중치와 뉴런의 값을 각각 곱하여 그 합이 다음 뉴런의 입력으로 쓰인다.
# (정확하게는 그 합에 활성화 함수(activation function)을 적용한 값이 다음 뉴런의 입력이 된다.)
# 이때, 각 층에서는 이전 뉴런의 값에 영향을 받지 않는 '정수'도 더해진다.(이 정수를 편향(bias)라고 함)

# 완전연결계층(fully connected layer) : 인접하는 층의 모든 뉴런과 연결되어 있다.

# 입력층의 데이터(x1,x2) 가중치 w11, w21, 편향 b1 ==> 은닉층 중 첫번째 뉴런은 다음과 같이 계산 가능
# h1 = x1*w11 + x2*w21 + b1

In [16]:
# 완전연결계층에 의한 변환의 미니배치 버전
import numpy as np
W1 = np.random.randn(2,4) # 가중치
print(W1)
b1 = np.random.randn(4) # 편향
x = np.random.randn(10, 2) # 입력
print(x)
h = np.matmul(x, W1) + b1
print(h)

[[ 1.81204266  0.15915402 -0.33646111  1.54672305]
 [ 0.67670207 -1.47193881  0.34844635  0.34299862]]
[[ 0.67359615 -1.02907758]
 [ 0.96312849 -2.22095356]
 [ 0.49902772 -1.05555115]
 [ 0.08101712 -1.76062916]
 [ 0.40282385 -0.93252104]
 [ 0.67947628 -0.37644115]
 [-0.57097253 -0.52440664]
 [ 0.69710686  0.83599647]
 [-0.5966374  -0.94863326]
 [-2.08416726 -1.61664319]]
[[ 0.57012046  1.40620414 -0.39743828  0.1120233 ]
 [ 0.28822047  3.20665289 -0.91015948  0.15103782]
 [ 0.23588031  1.41738835 -0.34792741 -0.1670661 ]
 [-0.99870049  2.38869197 -0.45296496 -1.05545353]
 [ 0.14480952  1.22098432 -0.27268916 -0.27366769]
 [ 1.02241593  0.44649909 -0.17200794  0.34497164]
 [-1.34357921  0.46528128  0.19716143 -1.63987833]
 [ 1.87482234 -1.33532892  0.24452952  0.78810569]
 [-1.67716008  1.08563224  0.05797644 -1.82508391]
 [-4.82467136  1.83215562  0.32570677 -4.35500713]]


In [ ]:
# 10개의 샘플 데이터 각각을 완전열결계층으로 변환
# 이러한 완전연결계층에 의한 변환은 '선형'변환'이다. 여기에 '비선형' 효과를 부여하는 것이
# 바로 '활성화 함수'이다. 정확히 말하면, 비선형 활성화 함수를 이용하여 신경망의 표현력을 높일 수 있다.
# 예에서는 시그모이드 함수(sigmoid function)을 사용해보자.

# 시그모이드 함수는 알파벳 S자 모양의 곡선 함수로 임의의 실수를 입력받아 0에서 1 사이의 실수를 출력한다.
def sigmoid(x) : 
  return 1 / (1+np.exp(-x))