<a href="https://colab.research.google.com/github/yeaeunJi/Algorithm_hackerrank/blob/main/Chapter1_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#벡터와 행렬
- 신경망에서는 '벡터'와 '행렬' 또는 '텐서(tensor)'가 중요함
  - 벡터 : 숫자가 일렬로 늘어선 집합(파이썬에서는 1차원 배열 취급 가능)
  - 행렬 : 2차원 형태로 숫자를 늘여놓은 것
  - 텐서 : 숫자집합을 N차원으로 표현한 것|



## 벡터 
- 벡터는 단순한 개념이지만 이를 표현하는 방법은 열벡터, 행벡터가 존재
  - 열벡터 : 숫자들을 세로로 나열하는 방법
  - 행벡터 : 숫잘들을 가로로 나열하는 방법
- 수학과 딥러닝 등 많은 분야에서 '열벡터'방식 선호하지만 이 책에서는 '행벡터'를 다룰 것임

In [5]:
# 벡터 생성 : np.array() 메소드로 생성 가능
import numpy as np
x = np.array([1,2,3]) # ==> numpy의 다차원 배열 클래스인 np.ndarray 클래스를 생성
print(x)
x.__class__ # 클래시 이름 표시.

[1 2 3]


numpy.ndarray

In [2]:
x.shape # 인스턴스 변수 중 다차원 배열의 형상(모양)에 관한 변수

(3,)

In [3]:
x.ndim # 인스턴스 변수 중 다차원 배열의 차원 수를 담고 있는 변수

1

In [4]:
# 행렬 생성
W = np.array([[1,2,3], [4,5,6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


## 행렬의 원소별 연산(elements-wise)
- 더하기(+)와 곱하기(*) 연산 : 피연산자인 다차원 배열들에서 서로 대응하는 원소끼리(각 원소가 독립적으로) 연산된다.

In [7]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
print(W+X)
print(W*X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


## 브로드캐스트(broadcast)
- 형상(모양)이 다른 다차원 배열끼리의 연산도 가능

In [9]:
A = np.array([[1,2], [3,4]])
A * 10 # 2차원 배열에 스칼라값을 곱할 경우, 스칼라 값이 A의 형상으로 확장되어 원소별 연산을 수행한다.

array([[10, 20],
       [30, 40]])

In [10]:
A = np.array([[1,2], [3,4]])
b = np.array([10, 20])
A * b # 2차원 배열A와 1차원 배열 b를 곱할 경우, 1차원 배열인 b가 2차원 배열 A의 형상과 같아지도록 활장되어 원소별 연산을 수행한다.

# 넘파이의 브로드캐스트가 효과적으로 동작하기 위해선 다차원 배열의 형상이 몇 가지 규칙을 충족해야 한다. 

array([[10, 40],
       [30, 80]])